//using TenJames.CompMap.Attributes;

using TenJames.CompMap.Attributes;
using TenJames.CompMap.Mappper;

namespace TenJames.CompMap.Example;


public class User {
    public int Id { get; set; }
    public string Name { get; set; }
    public Guid Guid { get; set; }
    public ICollection<Document> Documents { get; set; }
}


public class Document {
    public int Id { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }
}


[MapFrom(typeof(User))]
public partial class UserReadDto {
    public int Id { get; set; }
    public string Name { get; set; }
    public Guid Guid { get; set; }
    public required string Title { get; set; }
    public ICollection<DocumentDto> Documents { get; set; }

    private static partial UserUnmappedProperties GetUserUnmappedProperties(IMapper mapper, User source)
    {
        return new UserUnmappedProperties()
        {
            Title = source.Name + "'s Title",
        };
    }
}

[MapTo(typeof(User))]
public partial class UserCreateDto {
    public string Name { get; set; }
    public Guid Guid { get; set; }

    private static partial UserUnmappedProperties GetUserUnmappedProperties(IMapper mapper, UserCreateDto source)
    {
        return new UserUnmappedProperties()
        {

        };
    }
}

[MapFrom(typeof(Document))]
public partial class DocumentDto {
    public string Title { get; set; }
    public string Content { get; set; }
}

/*
 *Generated files
 *
 * UserReadDto.g.cs
 * ```cs
 *
 * <auto-generated/>
   using System;
   using System.Collections.Generic;

   using TenJames.CompMap.Mappper;

   namespace TenJames.CompMap.Example;

   partial class UserReadDto
   {

       ///<summary>
       /// The following properties were not mapped because they do not exist in the target class
       ///</summary>
       internal class UserUnmappedProperties
       {
           /// <summary>
           /// Found at /Entitities.cs at 29
           /// </summary>
           public required string Title { get; set; }
       }

       private static partial UserUnmappedProperties GetUserUnmappedProperties(IMapper mapper,  User source);

       /// <summary>
       /// Mapping method generated by TenJames.CompMap
       /// </summary>
       public static UserReadDto MapFrom(IMapper mapper, User source)
       {
           // Note: Some properties were not mapped due to missing counterparts in the target class.
           var unmapped = GetUserUnmappedProperties(mapper, source);
           return new UserReadDto
           {
               Id = source.Id,
               Name = source.Name,
               Guid = source.Guid,
               Documents = mapper.Map<ICollection<DocumentDto> >(source.Documents),
               Title = unmapped.Title,
           };
       }
   }
 * ```
 *
 * Others follow similar pattern
 *
 */
