using System;
using System.Text;

namespace TenJames.CompMap;

/// <summary>
/// SourceBuilder
/// </summary>
public class SourceBuilder  {
    private readonly StringBuilder sourceText;

    /// <summary>
    /// Basic Constructor
    /// </summary>
    public SourceBuilder()
    {
        sourceText = new StringBuilder();
        sourceText.AppendLine("// <auto-generated/>");
        sourceText.AppendLine("using System;");
        sourceText.AppendLine("using System.Collections.Generic;");
        sourceText.AppendLine();
    }
    private int indentLevel = 0;

    private string Indent => new string(' ', indentLevel * 4);

    /// <summary>
    /// Appends the empty line
    /// </summary>
    public void AppendLine() => AppendEmptyLine();

    /// <summary>
    /// Indents the line and appends it
    /// </summary>
    /// <param name="line">line to append</param>
    public void AppendLine(string line)
    {
        sourceText.Append(Indent);
        sourceText.AppendLine( line);
    }

    /// <summary>
    /// Increase the indent
    /// </summary>
    public void IncreaseIndent() => indentLevel++;

    /// <summary>
    /// Decrease the indent
    /// </summary>
    public void DecreaseIndent()
    {
        if (indentLevel > 0)
        {
            indentLevel--;
        }
    }

    /// <summary>
    /// Appends empty line
    /// </summary>
    public void AppendEmptyLine() => sourceText.AppendLine();

    /// <summary>
    /// Begins a code block
    /// </summary>
    /// <returns>Disposable block</returns>
    public Block BeginBlock() => new(this, "");

    /// <summary>
    /// Begins a named block
    /// </summary>
    /// <param name="headerLine"></param>
    /// <returns>Disposable block</returns>
    public Block BeginBlock(string headerLine) => new(this, headerLine);

    public override string ToString() => sourceText.ToString();


    public class Block : IDisposable
    {
        private readonly SourceBuilder _sourceBuilder;

        public Block(SourceBuilder sourceBuilder, string headerLine)
        {
            _sourceBuilder = sourceBuilder;
            _sourceBuilder.AppendLine(headerLine);
            _sourceBuilder.AppendLine("{");
            _sourceBuilder.IncreaseIndent();
        }

        public void Dispose()
        {
            _sourceBuilder.DecreaseIndent();
            _sourceBuilder.AppendLine("}");
        }
    }

}
