using System;
using System.Text;

namespace TenJames.CompMap;

public class SourceBuilder  {
    private readonly StringBuilder _sourceText;

    public SourceBuilder()
    {
        _sourceText = new StringBuilder();
        _sourceText.AppendLine("// <auto-generated/>");
        _sourceText.AppendLine("using System;");
        _sourceText.AppendLine("using System.Collections.Generic;");
        _sourceText.AppendLine();
    }
    private int _indentLevel = 0;
    
    private string Indent => new string(' ', _indentLevel * 4);

    public void AppendLine()
    {
        AppendEmptyLine();
    }
    public void AppendLine(string line)
    {
        _sourceText.Append(Indent);
        _sourceText.AppendLine( line);
    }

    public void IncreaseIndent()
    {
        _indentLevel++;
    }

    public void DecreaseIndent()
    {
        if (_indentLevel > 0)
            _indentLevel--;
    }
    
    public void AppendEmptyLine()
    {
        _sourceText.AppendLine();
    }

    public Block BeginBlock()
    {
        return new Block(this, "");
    }
    public Block BeginBlock(string headerLine)
    {
        return new Block(this, headerLine);
    }

    public override string ToString()
    {
        return _sourceText.ToString();
    }
    
    
    public class Block : IDisposable
    {
        private readonly SourceBuilder _sourceBuilder;

        public Block(SourceBuilder sourceBuilder, string headerLine)
        {
            _sourceBuilder = sourceBuilder;
            _sourceBuilder.AppendLine(headerLine);
            _sourceBuilder.AppendLine("{");
            _sourceBuilder.IncreaseIndent();
        }

        public void Dispose()
        {
            _sourceBuilder.DecreaseIndent();
            _sourceBuilder.AppendLine("}");
        }
    }
    
}